using FluentAssertions;
using HealthTrack.Domain.Entities;
using HealthTrack.Domain.Enums;
using HealthTrack.Domain.ValueObjects;

namespace HealthTrack.Domain.Tests.Entities;

public class PatientTests
{
    private static Patient CreateValidPatient() => new()
    {
        FirstName = "John",
        LastName = "Doe",
        DateOfBirth = new DateOfBirth(new DateTime(1990, 5, 15, 0, 0, 0, DateTimeKind.Utc)),
        Gender = Gender.Male,
        Email = "john.doe@example.com",
        Phone = new PhoneNumber("(555) 123-4567"),
        Address = new Address("123 Main St", "Springfield", "IL", "62701")
    };

    [Fact]
    public void Patient_Creation_ShouldSetRequiredProperties()
    {
        // Arrange & Act
        var patient = CreateValidPatient();

        // Assert
        patient.FirstName.Should().Be("John");
        patient.LastName.Should().Be("Doe");
        patient.Email.Should().Be("john.doe@example.com");
        patient.Gender.Should().Be(Gender.Male);
        patient.Phone.Number.Should().Be("(555) 123-4567");
        patient.Address.Street.Should().Be("123 Main St");
        patient.Address.City.Should().Be("Springfield");
        patient.Address.State.Should().Be("IL");
        patient.Address.ZipCode.Should().Be("62701");
    }

    [Fact]
    public void Patient_IsActive_ShouldDefaultToTrue()
    {
        // Arrange & Act
        var patient = CreateValidPatient();

        // Assert
        patient.IsActive.Should().BeTrue();
    }

    [Fact]
    public void Patient_Id_ShouldBeAutoGenerated()
    {
        // Arrange & Act
        var patient = CreateValidPatient();

        // Assert
        patient.Id.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void Patient_CreatedAt_ShouldBeSetToUtcNow()
    {
        // Arrange
        var before = DateTime.UtcNow;

        // Act
        var patient = CreateValidPatient();

        // Assert
        patient.CreatedAt.Should().BeOnOrAfter(before);
        patient.CreatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(2));
    }

    [Fact]
    public void Patient_Collections_ShouldBeInitializedEmpty()
    {
        // Arrange & Act
        var patient = CreateValidPatient();

        // Assert
        patient.Allergies.Should().NotBeNull().And.BeEmpty();
        patient.Medications.Should().NotBeNull().And.BeEmpty();
        patient.Appointments.Should().NotBeNull().And.BeEmpty();
        patient.Prescriptions.Should().NotBeNull().And.BeEmpty();
        patient.ClinicalNotes.Should().NotBeNull().And.BeEmpty();
        patient.Consents.Should().NotBeNull().And.BeEmpty();
    }

    [Fact]
    public void Patient_FullName_ShouldCombineFirstAndLastName()
    {
        // Arrange & Act
        var patient = CreateValidPatient();

        // Assert
        patient.FullName.Should().Be("John Doe");
    }

    [Fact]
    public void Patient_OptionalProperties_ShouldDefaultToNull()
    {
        // Arrange & Act
        var patient = CreateValidPatient();

        // Assert
        patient.InsuranceInfo.Should().BeNull();
        patient.EmergencyContact.Should().BeNull();
        patient.MedicalHistory.Should().BeNull();
        patient.ModifiedAt.Should().BeNull();
        patient.ModifiedBy.Should().BeNull();
        patient.CreatedBy.Should().BeNull();
    }

    [Fact]
    public void Patient_TwoInstances_ShouldHaveDifferentIds()
    {
        // Arrange & Act
        var patient1 = CreateValidPatient();
        var patient2 = CreateValidPatient();

        // Assert
        patient1.Id.Should().NotBe(patient2.Id);
    }
}
